### ISSUE TITLE
Contributor docs

### ISSUE THREAD

**Issue by dholbach** [kubereboot/website#2]
mention how to contribute  to the website,helm charts, and kured (the organisation's structure)?

_Originally posted by @evrardjp in https://github.com/kubereboot/website/pull/1#pullrequestreview-1113431684_

**Comment by dholbach** [comment]
@evrardjp

**Comment by evrardjp** [comment]
I think this is good enough.

**Comment by evrardjp** [comment]
If anyone wants to have more details in the contributing documentation, they can submit a MR :)
